### ISSUE TITLE
Labels på issues

### ISSUE THREAD

**Issue by gosiacodes** [nathaliedpettersson/vh-slut_vg#26]
Använda gärna labels på issues och glöm inte stänga älla som är färdiga innan du avslutar projektet.

**Comment by nathaliedpettersson** [comment]
Tack för feedback! Angående labels så hade jag missförstått att man kunde skapa sina egna. Pratade med Johan idag efter att jag förvirrat inte hade hittat de som han använt under mina "labels". Men förstår absolut syftet med labels och att det är lättare att filtrera på vad som är vad, så det tar jag till mig till nästa projekt.

Issues ska stängas när hela projektet är 100% klart och alla granskningar har blivit gjorda, den tasken är fortfarande under "to do".
