### ISSUE TITLE
Glöm inte stänga ALLA branches!

### ISSUE THREAD

**Issue by gosiacodes** [nathaliedpettersson/vh-slut_vg#27]
Det är viktigt att du gör det! Om du kollar branches som var skapade av Johan, ska du hitta det som skulle finnas i projektet :smiley: (som var markerad som "done" i tasks) 🕵🏻‍♀️ 🤓

**Comment by nathaliedpettersson** [comment]
Haha, denna har blivit en liten miss av mig och feltolkning som upptäcktes idag i skolan. Johan är medveten om detta och vi har löst det på annat vis pga det strulade med Mac när merging skulle göras i efterhand...

Tack för jättebra och användbar feedback, det visar på att du är noga när du granskar!

**Comment by gosiacodes** [comment]
OK, så hur du ska lösa det? Undrar bara 😸 Ska du göra de ändringar som saknas i din egen branch eller? (t.ex. copyright BUG 🐛)

**Comment by nathaliedpettersson** [comment]
Nej jag ska göra egen kommentar om det vid inlämning pga. kan inte välja enstaka saker jag ska behålla/ta bort på samma sätt utan Git Extensions. Jag har inte tolkat issuet "Merga alla grenar" på det viset det skulle ha blivit tolkat på, men jag har gjort ting utifrån min tolkning vilket var okej. Väljer därför att se bort helt ifrån innehållet som ej var en del av release-branchen från start :thumbsup:

Angående BUG: Copyright så tolkar jag den issuen som att det var tecknet som var fel. Alltså att han har (c) vilket inte är  ett riktigt tecken för copyright, något jag ändrat på min sida :relaxed:
