### ISSUE TITLE
Saknas Helvetica som "main" font 

### ISSUE THREAD

**Issue by gosiacodes** [nathaliedpettersson/vh-slut_vg#29]
Du stängde issue #10 (All brödtext ska vara helvetica), men jag kan inte hitta var det gjordes? Det finns Helvetica, men inte som "main" font och syns inte på sidan.
Om du ändrar från: font-family: Arial, Helvetica, sans-serif; till font-family: Helvetica, Arial, sans-serif; blir Helvetica som första val.

**Comment by nathaliedpettersson** [comment]
Det visste jag faktiskt inte att det blev så! Jag fick automatiskt upp den där när jag skrev Helvetica, men det tar jag till mig och ändrar med en gång :)
