### ISSUE TITLE
Bra jobbat!

### ISSUE THREAD

**Issue by gosiacodes** [nathaliedpettersson/vh-slut_vg#30]
Du gjorde projektet nästan enligt kundens önskemål. Färgschema passar bra, alla sidorna är med och följer samma struktur.
I framtiden försök att ha bättre koll på branches som du tar över från din kollega 😉 Det är bra att du har flera branches, det går bra att dela dem i mindre branches med små tasks / issues eller skapa ny branch för varje task / issue / feature om de är större, så det är lättare att följa med projektet och ens versioner.
Bra jobbat Nathalie! 😃

**Comment by nathaliedpettersson** [comment]
Tusen tack Gosia! Och tack för att du tog dig tid att ge mig mycket nyttig feedback till nästa gång :star: 
Så användbart och tacksamt att få göra denna övningen och att få ta del av feedback samt granska din kod och ditt projekt. 
Det är nyttigt att se att alla tänker olika och tolkar olika fast att vi alla utgått från samma projekt :relieved:
Och jag har definitivt lärt mig MYCKET som ska tänkas på nästa gång jag jobbar med GitHub och versionshantering!
